### ISSUE TITLE
Subxt functions failing for Aleph Zero mainnet

### ISSUE THREAD

**Issue by miloskriz** [turboflakes/crunch#22]
Dear Paulo, I hope this case finds you well, 

For your kind consideration, this is the issue we are facing with the mainnet of Aleph Zero, this network is implementing the runtime version `aleph-node/46` and both, the local ws:// endpoint, and Crunch's metadata, are up to date with the appropriate versions.

The first symptom are shown in the logs as:

```
[WARN  crunch::runtimes::aleph_zero] Crunch upgrade might be required soon. Local static metadata differs from current chain runtime version.
[INFO  crunch::report] <details><summary>Next era expect <b>NO</b> rewards 🙁</summary>
```
(apart of the WARN, please note the absence of the `Earlier claimed` comment in the INFO block.

After which the bot runs without apparent problems and even hooks OK with the paidEras() event, but it fails to retrieve the pending payments and process no payouts at all.

Thus, with the help of another [community member](https://twitter.com/therealsc0t), it was determined that at least two functions seem to be failing in the aleph_zero.rs file:

- `node_runtime::validate_codegen`
- `node_runtime::storage().staking().history_depth()`, and/or 
- `crunch.client().clone().storage().fetch()` for the above `history_depth_addr`

Do you have an idea were to start looking for a solution?

Please advise!

Best regards...

**_Milos_**

**Comment by paulormart** [comment]
fixed by #23
