### ISSUE TITLE
OpenSSL error, File not found

### ISSUE THREAD

**Issue by m-saxemberg** [turboflakes/crunch#26]
Starting from version 0.8.1 the following error is found
crunch: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory.
It seems like support for OpenSSL v1 which is the default in Debian

**Comment by paulormart** [comment]
Hi, you can try to upgrade openssl or use the binary from the latest release [v0.8.3](https://github.com/turboflakes/crunch/releases/tag/v0.8.3)

**Comment by m-saxemberg** [comment]
> Hi, you can try to upgrade openssl or use the binary from the latest release [v0.8.3](https://github.com/turboflakes/crunch/releases/tag/v0.8.3)

Upgraded to version 0.8.3 and it works. The issue was opened when 0.8.0 and 0.8.1 were the latest versions.
We're happy that since 0.8.3 OpenSSL v1 is supported again.
