### ISSUE TITLE
libssl.so.1.1 library issue on Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by alam807** [turboflakes/crunch#29]
The service fails to start with "/crunch-bot/crunch: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory...". Why am I getting this error? how do I fix this? 

I am using [Crunch v0.9.3]

Cheers!

**Comment by paulormart** [comment]
Hi,

You could either build from source on your environment or try to install previous openssl version:

```
wget https://mirror.umd.edu/ubuntu/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
dpkg -i libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
```

**Comment by alam807** [comment]
That was it! Thanks!
