### ISSUE TITLE
'async-std/runtime' panicked

### ISSUE THREAD

**Issue by Party-Animal** [turboflakes/crunch#30]
Hi all, i am getting this error when trying to start up crunch. Any idea how i can resolve it? Many thanks

[2023-05-10T06:39:16Z WARN  crunch::runtimes::kusama] Crunch upgrade might be required soon. Local static metadata differs from current chain runtime version.
thread 'async-std/runtime' panicked at 'constructed from known-good static value; qed: InvalidFormat', src/crunch.rs:134:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'task has failed', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.3.0/src/task.rs:426:43

**Comment by paulormart** [comment]
Hi, are you running the latest binary released or are you building from source?
