### ISSUE TITLE
Support docker/podman

### ISSUE THREAD

**Issue by leeclemens** [turboflakes/crunch#32]
Add `Dockerfile` for basic docker/podman support

(If accepted, I'll happily update `README.md` as well)

**Comment by paulormart** [comment]
Hey looks great. Yes, please feel free to add some examples to readme. I'll merge it.

Thanks

**Comment by leeclemens** [comment]
Cool! I updated README and moved Dockerfile to the root so that it will work with `docker build`. I had originally used `buildah`.
