### ISSUE TITLE
Pool permissionless claiming

### ISSUE THREAD

**Issue by queiroz** [turboflakes/crunch#35]
Hi, I thought crunchbot would claim pool nominees rewards as well as compound them based on the new permissionless claiming feature, but apparently all it does is claim rewards for the validator the pool is nominating.

Are there any plans for such functionality?

<img width="590" alt="Screenshot 2023-07-04 at 17 53 07" src="https://github.com/turboflakes/crunch/assets/670685/fafd1956-ddd0-4d10-a49f-5fafee701087">

**Comment by paulormart** [comment]
Just to leave it here, permissionless auto-compound for members is already implemented in [v0.10.1](https://github.com/turboflakes/crunch/releases/tag/v0.10.1)

To claim the pool commission permissionless is not possible at a moment, so i'll close this issue for now, and we can open a new one as soon as an extrinsic is available.
