### ISSUE TITLE
Build error:  unresolved import `async_task::Builder`

### ISSUE THREAD

**Issue by ScepticMatt** [turboflakes/crunch#40]
Seems like a missing dependency. Using rust 1.74

 ```unresolved import `async_task::Builder`
  --> /home/payment/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:46:18
   |
46 | use async_task::{Builder, Runnable};
   |                  ^^^^^^^ no `Builder` in the root
   |
   = help: consider importing this struct instead:
           std::thread::Builder

For more information about this error, try `rustc --explain E0432`.
error: could not compile `async-executor` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by paulormart** [comment]
Hi, I tried with the rust version 1.74.0 and the outcome was successful. This is what i did:
```
rustup install 1.74
cargo clean
cargo +1.74.0 build
```
...
```
Compiling crunch v0.12.2
Finished dev [unoptimized + debuginfo] target(s) in 1m 52s`
```
