### ISSUE TITLE
Crunch crashes when there is already a transaction in the pool

### ISSUE THREAD

**Issue by gregorst3** [turboflakes/crunch#44]
Hi there! I want to report a small bug. When we initialize the Crunch Bot and it starts collecting rewards, if we kill and restart it, the bot crashes. This happens because the old transaction it made to collect rewards is still in the waiting pool. When we restart the bot, it tries to collect rewards again, but there is already a transaction (with the same fees) in the awaiting pool. 

`[2024-06-22T10:02:12Z ERROR crunch::crunch] Subxt error: Rpc error: RPC error: ErrorObject { code: ServerError(1014), message: "Priority is too low: (1 vs 1)", data: Some(RawValue("The transaction has too low priority to replace another transaction already in the pool.")) }
thread 'async-std/runtime' panicked at src/crunch.rs:464:76:`

**Comment by paulormart** [comment]
Hi @gregorst3 this issue on Kusama is related to the number of payouts included in the same batch call, to fix it set the value of _CRUNCH_MAXIMUM_PAYOUTS=3_
