### ISSUE TITLE
ServerErrror: Priority is too low

### ISSUE THREAD

**Issue by ScepticMatt** [turboflakes/crunch#45]
```Subxt error: Rpc error: RPC error: ErrorObject { code: ServerError(1014), message: "Priority is too low: (2 vs 2)", data: Some(RawValue("The transaction has too low priority to replace another transaction already in the pool.")) }```

How can I configure the transaction priority?

**Comment by paulormart** [comment]
Hey, try to lower the number of payouts included in a single batch. Is defined by this environment variable `CRUNCH_MAXIMUM_CALLS=2`. If your currently value is 3 setting it with 2 should fix the issue.

**Comment by ScepticMatt** [comment]
Thank you, will try that
