### ISSUE TITLE
Dependency on libssl1.1 (OpenSSL 1.1.1) 

### ISSUE THREAD

**Issue by SafeStakeIo** [turboflakes/crunch#51]
I found the crunch bot is depending libssl1.1 (OpenSSL 1.1.1) to run. OpenSSL 1.1.1 reached its end of life on September 11, 2023. Are you planning to upgrade to use the libssl3 (OpenSSL 3.x)  instead?

I get the following error when try to start the service:

Nov 18 12:38:57 xxxxxxxxxx crunch[1777]: /crunch-bot/crunch: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Nov 18 12:38:57 xxxxxxxxxx systemd[1]: crunch.service: Main process exited, code=exited, status=127/n/a
Nov 18 12:38:57 xxxxxxxxxx systemd[1]: crunch.service: Failed with result 'exit-code'.

**Comment by paulormart** [comment]
Hey could you let me know which OS are you using?

**Comment by SafeStakeIo** [comment]
I am currently using the Ubuntu 22.04.5 LTS.

**Comment by paulormart** [comment]
Ok, the binary available on the release is being compiled under Ubuntu-20.04 and when used on Ubuntu 22.04.5 LTS it raises the issue. There were some incompatibilities with Debian users also, I'll have a look again.

As a workaround you can always compile from source or install previous [libssl1.1.1](https://github.com/turboflakes/crunch/tree/main?tab=readme-ov-file#common-issue-on-ubuntu-2204-when-using-the-crunch-binary) in the meantime.

**Comment by SafeStakeIo** [comment]
I am using the workaround for now (it won't be a safe long-term solution), but I would love to upgrade as soon as a release that uses the libssl3 (OpenSSL 3.x). Thank you.
