### ISSUE TITLE
License conflict with subxt?

### ISSUE THREAD

**Issue by moh-eulith** [turboflakes/crunch#7]
subxt is licensed as GPL v3. This project is MIT.

**Comment by leeclemens** [comment]
@moh-eulith https://www.gnu.org/licenses/license-list.html#Expat is listed under "GPL-Compatible Free Software Licenses". Did you have a specific concern?

**Comment by moh-eulith** [comment]
Including an MIT component into a GPL licensed code base is indeed compatible, but that's not the situation here. The reverse, having a GPL component inside an MIT licensed code base is not allowed, which is the situation for this code base.
Please see the [explanation](https://en.wikipedia.org/wiki/License_compatibility#Compatibility_of_FOSS_licenses) of one-way compatibility. The diagram in that section is helpful, as is the text description below it.

**Comment by leeclemens** [comment]
A step back, what GPL licensed code is being distributed in this project?

**Comment by moh-eulith** [comment]
subxt is being linked.

**Comment by leeclemens** [comment]
What is "linked". #IANAL but is it being distributed?

**Comment by moh-eulith** [comment]
[Linked](https://en.wikipedia.org/wiki/Linker_(computing)), which is referenced from the license compatibility section of that wikipedia article. #IANAL has never been a defense of illegal behavior.

**Comment by leeclemens** [comment]
@moh-eulith  Sorry, are you accusing me of illegal behavior?

**Comment by mohrezaei** [comment]
I'm not accusing any particular person of any particular thing. I was trying to be helpful: the project (not you personally) is not in compliance of license requirements as I interpret them. It's entirely up to you if you (a) agree with that interpretation and (b) want to fix it.

**Comment by moh-eulith** [comment]
No, I'm not accusing you personally of anything. I was trying to be helpful: the project (not you personally) is not in compliance with license requirements as I interpret them. It's entirely up to you if you (a) agree with that interpretation and (b) want to fix it.

**Comment by leeclemens** [comment]
@moh-eulith and I'm also trying to be helpful and attempting to understand what issue you think there is, exactly. What code is being distributed here under a different license? It's starting to feel like twitter, but I'm truly trying to have an honest and good faith discussion to understand your issue.

I guess you responded with your other account by mistake? Any way I can I know who I am actually talking to that is accusing me of illegal behavior?

**Comment by leeclemens** [comment]
![Screenshot from 2023-09-17 00-42-33](https://github.com/turboflakes/crunch/assets/1250267/6e787721-7560-4a0f-a61e-aa6a3e1f5113)

**Comment by moh-eulith** [comment]
[Aside: I use multiple github accounts for legal reasons: each account is under a different copyright holder.]

Here is a longer explanation of this issue:
When I choose to use a project as either a library or a binary, I look at the license. It's one of the few fields that github lists on the front page of the project. That's important. I have to make sure that I'm in compliance with license terms.

It is impossible to build a binary of this project that is licensed under MIT, despite the fact that the github page for this project claims it's licensed as such. If I was in an environment that precluded usage of GPL binaries I might easily make the mistake of labeling the combined work as MIT.

The work itself contains a clear reference (via Cargo.toml and various files with import statements) to GPL code. Github provides public distribution of those files, which in my opinion, are incorrectly licensed.

**Comment by leeclemens** [comment]
@moh-eulith I'll just ask one more time out of curiosity (because you implied wrongdoing on my part). What code do you believe is distributed as part of this project that is ... I don't know ... illegitimately licensed, in your view?

You seem to misunderstand everything. I'm guessing you are also not a lawyer?

github is not "claiming" the license is anything. It's merely reflecting the license provided with this software project based on its owners input. Are you disputing that?

I've never heard of someone using different github accounts based on being under different copyright holders. It's quite interesting. May I know what country you are from? Perhaps different jurisdictions have different interpretations.

**Comment by moh-eulith** [comment]
I'm sorry, I don't think this discussion will be helpful for anyone. If you have access to a lawyer, I would humbly suggest you consult them. Feel free to close the issue.

**Comment by leeclemens** [comment]
okay mohammad (@mohrezaei, @moh-eulith), I'll be sure to do that. Thank you for your baseless and unsupported legal implications against me. I'm sorry this trail muddied this project's Issues notifications, it was never my intention (I just wanted to understand the concern).

**Comment by paulormart** [comment]
Thank you both for the discussion on this open issue. I've changed crunch license to [Apache 2.0](https://github.com/turboflakes/crunch/blob/main/LICENSE) same as [subxt](https://github.com/paritytech/subxt/blob/master/LICENSE).

I'm closing this issue, feel free to reopen if need.
